apiVersion: v1
kind: Service
metadata:
  name: my-webpage
  labels:
	app: my-webpage
spec:
  ports:
	- nodePort: 30000
  	port: 80
  	targetPort: 80
  selector:
	app: my-webpage
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: my-webpage
  labels:
	app: my-webpage
spec:
  replicas: 2
  selector:
	matchLabels:
  	app: my-webpage
  strategy:
	type: RollingUpdate
  template:
	metadata:
  	labels:
    	app: my-webpage
	spec:
  	containers:
  	- image: devwrat/my_httpd_php_ipmem_liveclock
